AWSTemplateFormatVersion: 2010-09-09
Description: Academy CloudFormation checkpoint
Parameters:
  DefaultParametri:
    Type: String
    Default: Inka
  AmiId:
    Type: String
    Default: ami-07eda9385feb1e969

Resources:
  InstanssiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Security group for EC2 instance'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  Instanssi:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: AmiId
      InstanceType: t2.nano
      SecurityGroups:
        - !Ref InstanssiSecurityGroup
      Tags:
        - Key: Owner
          Value: Inka
      UserData:
        Fn::Base64:
          Fn::Join:
            - "\n"
            - - "#!/bin/bash"
              - "amazon-linux-extras install epel"
              - "amazon-linux-extras install nginx1"
              - "systemctl start nginx"
  InkaBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Owner
          Value:
            Ref: DefaultParametri
  SsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: arn:aws:s3:::InkaBucket
Outputs:
  Instanssi:
    Value: !GetAtt Instanssi.PublicDnsName
